# Generated by Django 5.1.4 on 2024-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=50)),
                ('contactEmail', models.CharField(max_length=50)),
                ('contactPhone', models.CharField(max_length=50)),
                ('contactWebName', models.CharField(max_length=50)),
                ('contactMessage', models.TextField()),
            ],
        ),
    ]
